version: '3.4'

services:
  aplication:
    build:
      context: KelloWorld
      dockerfile: Dockerfile
    image: kelloworls:1.0.1
    container_name: kelloworls.container
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    environment:
      - MYSQL__SERVER=mysql_db
      - MYSQL__DATABASE=kelloworld
      - MYSQL__USER=strong_user
      - MYSQL__PASSWORD=strong_pass
      - Logging__LogLevel__Default=Debug
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=kelloworld
      - MYSQL_USER=strong_user
      - MYSQL_PASSWORD=strong_pass
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

volumes:
  mysqldata:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge 