version: '3.4'

services:
  aplication:
    build:
      context: KelloWorld
      dockerfile: Dockerfile
    image: kelloworls:1.0.1
    container_name: kelloworls.container
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend
    environment:
      - PSQL__SERVER=psql_db
      - PSQL__DATABASE=kelloworld
      - PSQL__USER=strong_user
      - PSQL__PASSWORD=strong_pass
      - Logging__LogLevel__Default=Debug
    depends_on:
      - psql_db

  psql_db:
    image: postgres:10.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=strong_pass
      - POSTGRES_USER=strong_user
      - POSTGRES_DB=kelloworld
    volumes:
      - psqldata:/var/lib/mysql
    ports:
      - 5432:5432
    networks:
      - backend

volumes:
  psqldata:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge 