version: '3.4'

services:
  kelloworld:
    image: ${DOCKER_REGISTRY-}kelloworld
    build:
      context: ./KelloWorld
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8080:80"
    environment:
      - PostgreSQL__ConnectionString=server=psql_db;port=5432;userid=strong_user;database=kelloworld;
      - PostgreSQL__DbPassword=strong_pass
      - Logging__LogLevel__Default=Debug
    depends_on:
      - psql_db

  psql_db:
    image: postgres:10.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=strong_pass
      - POSTGRES_USER=strong_user
      - POSTGRES_DB=kelloworld
    volumes:
      - psqldata:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - backend

volumes:
  psqldata:
    driver: local

networks:
  backend:
    driver: bridge 
