---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: 'kelloworls:1.0.1'
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: app-port
          env:
            - name: MYSQL__SERVER
              value: mysql
            - name: MYSQL__DATABASE
              value: "kelloworld"
            - name: MYSQL__USER
              value: "strong_user"
            - name: MYSQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 80
      nodePort: 30475 
  selector:
    app: application