---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: mvoronoy/kelloworld:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: app-port
          env:
            - name: PostgreSQL__ConnectionString
              value: "server=postgres;port=5432;userid=postgres;database=kelloworld;"
            - name: PostgreSql__DbPassword
              valueFrom:
                secretKeyRef:
                  name: psql
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 80
      nodePort: 30475 
  selector:
    app: application